name: Branch build

on:
  push:
    branches-ignore:
      - 'test-*'

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:

    - name: Set up Go 1.17
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
      id: go

    - name: Check out code
      uses: actions/checkout@v1

    - name: Install windows build helpers
      if: startsWith(matrix.os, 'windows')
      run: choco install mingw

    - name: Install libcurl
      if: startsWith(matrix.os, 'ubuntu')
      run: sudo apt install libcurl4-openssl-dev

    - name: Run tests
      run: go run ./rig.go
      working-directory: ./testrig

